version: '2'

services:
  executor:
    image: com.devsoap/dbt-executor
    container_name: dbt-executor
    environment:
    - dbt.ledger.url=http://ledger:5050
  ledger:
    image: com.devsoap/dbt-ledger
    container_name: dbt-ledger
    environment:
    - dbt.executor.url=http://executor:5050